{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "llm-comparison.envoyName" $ }}-ingress
  namespace: {{ include "llm-comparison.namespace" $ }}
  labels:
    {{- include "llm-comparison.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className | quote }}
  {{- end }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- toYaml $.Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ include "llm-comparison.envoyName" $ }}
            port:
              name: http
      {{- end }}
{{- end }}
{{- end }}
